name: Deploy Azure Function

on:
  workflow_dispatch:

env:
  NODE_VERSION: '14.x'
  AZUREFUNCDEST: 'https://bucketc2c.blob.core.windows.net/new-files'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install azcopy
        uses: kheiakiyama/install-azcopy-action@v1.0.3

      # Delete all files in the container
      - name: Empty the bucket
        run: azcopy remove '${{ env.AZUREFUNCDEST }}?${{ secrets.SAS_TOKEN }}' --recursive

      # Copy the contents of the azure functions
      - name: Copy new files
        run: azcopy copy 'Folder/*' '${{ env.AZUREFUNCDEST }}?${{ secrets.SAS_TOKEN }}' --recursive --from-to=LocalBlob

      # Install Azure CLI
      - name: Install Azure CLI
        run: |
          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash

      # Purge CDN cache
      - name: Purge CDN cache
        run: az cdn endpoint purge -g <RESOURCE_GROUP_NAME> -n <ENDPOINT_NAME> --profile-name <PROFILE_NAME> --content-paths '/*'
        env:
          AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
